# Generated by Django 4.0.5 on 2022-06-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'savings'), ('C', 'credit')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AccountProfile.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('limit', models.DecimalField(decimal_places=2, default=-20000, editable=False, max_digits=7)),
            ],
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('limit', models.DecimalField(decimal_places=2, default=50, editable=False, max_digits=7)),
            ],
            bases=('account.account',),
        ),
    ]
