# Generated by Django 4.0.5 on 2022-06-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('D', 'deposit'), ('W', 'withdraw')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
        ),
    ]
